### ISSUE TITLE
Create Survey Epic

### ISSUE THREAD

**Issue by AashnaNarang** [AashnaNarang/SYSC4806#12]
Technical Design 
- [x] https://github.com/AashnaNarang/SYSC4806/issues/28

Backend
- [x] https://github.com/AashnaNarang/SYSC4806/issues/5
- [x] https://github.com/AashnaNarang/SYSC4806/issues/11
- [x] https://github.com/AashnaNarang/SYSC4806/issues/10

Frontend
- [x] https://github.com/AashnaNarang/SYSC4806/issues/9
- [x] https://github.com/AashnaNarang/SYSC4806/issues/8
- [x] https://github.com/AashnaNarang/SYSC4806/issues/7
- [x] https://github.com/AashnaNarang/SYSC4806/issues/6
