### ISSUE TITLE
Use Survey Epic

### ISSUE THREAD

**Issue by AashnaNarang** [AashnaNarang/SYSC4806#29]
Technical Design:
- [x] https://github.com/AashnaNarang/SYSC4806/issues/30

Backend:

- [x] https://github.com/AashnaNarang/SYSC4806/issues/40
- [x] https://github.com/AashnaNarang/SYSC4806/issues/31
- [x] https://github.com/AashnaNarang/SYSC4806/issues/32
- [x] https://github.com/AashnaNarang/SYSC4806/issues/33
- [x] https://github.com/AashnaNarang/SYSC4806/issues/38

Frontend:

- [x] https://github.com/AashnaNarang/SYSC4806/issues/34
- [x] https://github.com/AashnaNarang/SYSC4806/issues/35
- [x] https://github.com/AashnaNarang/SYSC4806/issues/36
- [x] https://github.com/AashnaNarang/SYSC4806/issues/37
