### ISSUE TITLE
Dashboard Epic

### ISSUE THREAD

**Issue by AashnaNarang** [AashnaNarang/SYSC4806#63]
To do:

Tech Doc
- [x] https://github.com/AashnaNarang/SYSC4806/issues/70

Backend
- [x] https://github.com/AashnaNarang/SYSC4806/issues/65

Frontend
- [x] https://github.com/AashnaNarang/SYSC4806/issues/66
- [x] https://github.com/AashnaNarang/SYSC4806/issues/67
- [x] https://github.com/AashnaNarang/SYSC4806/issues/68
