### ISSUE TITLE
Metrics Epic

### ISSUE THREAD

**Issue by AashnaNarang** [AashnaNarang/SYSC4806#64]
To do:

Tech Doc:
- [x] https://github.com/AashnaNarang/SYSC4806/issues/69

Backend:
- [x] https://github.com/AashnaNarang/SYSC4806/issues/71

Frontend:
- [x] https://github.com/AashnaNarang/SYSC4806/issues/72
- [x] https://github.com/AashnaNarang/SYSC4806/issues/73
- [x] https://github.com/AashnaNarang/SYSC4806/issues/74
